"""The source side of the loader: SQL Server reads, and the correctness that makes them
safe to advance a watermark past -- plus, on the high-water tables, the point where
that correctness runs out.

Three things in this module are the actual engineering content of the exercise. Each is
a bug that produces no error message, which is why each gets a named function and a
test rather than a comment.

  1. BOUNDED high-water reads (`read_high_water`). An open-ended `id > last_id` with
     the ceiling taken after the read loses rows permanently, silently. The bound closes
     that race. It does NOT make an IDENTITY watermark safe under concurrent writers --
     that hole is measured and written up in `high_water_ceiling`, and the scorecard's
     contiguity check is what catches it in flight.
  2. INSTANCE IDENTITY on the watermark (`source_fingerprint`). Without it, a rebuilt
     source makes every check pass against a database that no longer exists.
  3. A SINGLE SNAPSHOT for the version stamp and the row read (`snapshot`). Taking the
     stamp outside the read is either lost rows or a double-apply with a stale value,
     depending on which side you get wrong.
"""

from __future__ import annotations

import re
import time
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator, Sequence

import pymssql

from .config import SourceConfig, TableSpec

# A `GO` on a line of its own, optionally followed by a batch count or trailing
# whitespace. GO is a client batch separator, not T-SQL -- pymssql has never heard of
# it. Splitting here rather than removing GO from the .sql files keeps those files
# copy-pasteable into SSMS, Azure Data Studio or sqlcmd unchanged, and some statements
# (CREATE DATABASE, ALTER DATABASE ... SET, USE) genuinely require their own batch.
_GO_SEPARATOR = re.compile(r"^\s*GO\s*(?:\d+\s*)?$", re.IGNORECASE | re.MULTILINE)


def split_batches(script: str) -> list[str]:
    """Split a T-SQL script on GO into executable batches, dropping empty ones."""
    return [b for b in (raw.strip() for raw in _GO_SEPARATOR.split(script)) if b]


@dataclass(frozen=True)
class ChangeRow:
    """One row from a change-tracking feed.

    `operation` is 'I', 'U' or 'D'. A 'D' carries only the primary key: the row is gone
    from the base table, so there is nothing else to select. That is the entire reason
    change tracking is used for these tables -- no watermark strategy can represent a
    row that no longer exists.
    """

    operation: str
    key: tuple[Any, ...]
    values: dict[str, Any] | None


@dataclass(frozen=True)
class SourceFingerprint:
    """Identifies this incarnation of the source database.

    THE BUG THIS EXISTS TO PREVENT, which is the single most likely way a reviewer's
    second run produces a false green:

      `docker compose down -v && docker compose up` rebuilds the source from scratch.
      Change-tracking versions restart at 0. But the warehouse -- if its volume
      outlives the source's, or if only the source was reset -- still records "I am
      caught up to version 47". Ask for changes since 47 on a database whose current
      version is 3 and the feed is empty. No error. The validity check passes, because
      MIN_VALID_VERSION is 0 and 0 <= 47. Every check then goes green against a
      database that was completely rebuilt and holds none of the data the warehouse
      claims to mirror.

      Re-running is the first thing anyone does, so this is not a theoretical failure.

    The fix: stamp which database incarnation each watermark belongs to, and refuse to
    use a watermark from a different one. `service_broker_guid` is regenerated by
    CREATE DATABASE, and create_date moves with it -- together they cannot survive a
    rebuild. Refusing costs a full reseed; not refusing costs a silently wrong
    warehouse, which is strictly worse.
    """

    server_name: str
    database_guid: str
    database_created_at: str

    @property
    def token(self) -> str:
        return f"{self.server_name}|{self.database_guid}|{self.database_created_at}"


class Source:
    """A connection to the stand-in production SQL Server."""

    def __init__(self, config: SourceConfig) -> None:
        self._config = config
        self._conn: pymssql.Connection | None = None

    # ── connection ──────────────────────────────────────────────────────────────────

    def connect(self, *, database: str | None = None, wait: bool = True) -> None:
        """Connect, optionally waiting for the server to become reachable.

        This is the pipeline's authoritative readiness gate -- see the note on
        SourceConfig.connect_timeout_seconds for why it is here and not a compose
        healthcheck condition. The loop distinguishes "not up yet" from "up and
        rejecting me", because retrying a bad password for three minutes and then
        reporting a timeout sends the reader looking in entirely the wrong place.
        """
        target_db = database or self._config.database
        deadline = time.monotonic() + (self._config.connect_timeout_seconds if wait else 0)
        attempt = 0
        last_error: Exception | None = None

        while True:
            attempt += 1
            try:
                self._conn = pymssql.connect(
                    server=self._config.host,
                    port=str(self._config.port),
                    user=self._config.user,
                    password=self._config.password,
                    database=target_db,
                    autocommit=True,
                    login_timeout=10,
                    timeout=300,      # a 250k-row seed statement is not a hung query
                    charset="UTF-8",
                )
                return
            except pymssql.Error as exc:
                last_error = exc
                message = str(exc)

                # Login failed / password rejected: the server is up and answering.
                # Retrying cannot help, and pretending it might buries the real cause.
                if "Login failed" in message or "18456" in message:
                    raise SystemExit(
                        f"SQL Server rejected the login for user "
                        f"{self._config.user!r}.\n"
                        f"  Check MSSQL_SA_PASSWORD in .env matches what the mssql "
                        f"container was started with. If you changed it after the first "
                        f"`up`, the password is baked into the existing data volume -- "
                        f"run `docker compose down -v` to discard it.\n"
                        f"  Driver said: {message}"
                    ) from exc

                if time.monotonic() >= deadline:
                    break
                if attempt == 1:
                    print(
                        f"  waiting for SQL Server at {self._config.host}:"
                        f"{self._config.port} (up to "
                        f"{self._config.connect_timeout_seconds}s; a cold start pulls a "
                        f"~1.6 GB image and then runs recovery)",
                        flush=True,
                    )
                time.sleep(self._config.connect_retry_interval_seconds)

        raise SystemExit(
            f"Could not reach SQL Server at {self._config.host}:{self._config.port} "
            f"within {self._config.connect_timeout_seconds}s after {attempt} attempts.\n"
            f"  Most common causes, in order:\n"
            f"    * the container was OOM-killed -- SQL Server on Linux needs 2 GB and "
            f"below that floor it appears to boot and then dies with the reason buried "
            f"in the container log. Try `docker compose logs mssql`.\n"
            f"    * on Apple Silicon: there is no arm64 SQL Server image, so this runs "
            f"under emulation Microsoft does not test. See README.\n"
            f"  Driver said: {last_error}"
        )

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    @property
    def connection(self) -> pymssql.Connection:
        if self._conn is None:
            raise RuntimeError("Source.connect() has not been called")
        return self._conn

    # ── script execution ────────────────────────────────────────────────────────────

    def execute_script(self, path: Path) -> list[list[dict[str, Any]]]:
        """Run a .sql file, honouring GO batch separators.

        Returns the result sets of any batch that produced rows, so a script can emit
        its own evidence into the transcript (03_enable_capture.sql ends with a SELECT
        of the tables it just enabled, rather than the reader taking the file's word).
        """
        script = path.read_text(encoding="utf-8")
        results: list[list[dict[str, Any]]] = []

        for index, batch in enumerate(split_batches(script), start=1):
            with self.connection.cursor(as_dict=True) as cursor:
                try:
                    cursor.execute(batch)
                except pymssql.Error as exc:
                    first_line = batch.splitlines()[0][:120] if batch.splitlines() else ""
                    raise SystemExit(
                        f"{path.name}: batch {index} failed.\n"
                        f"  Batch began: {first_line}\n"
                        f"  SQL Server said: {exc}"
                    ) from exc
                try:
                    rows = cursor.fetchall()
                except pymssql.Error:
                    rows = []          # a batch that returns no result set
                if rows:
                    results.append(rows)
        return results

    def query(self, sql: str, params: Sequence[Any] | None = None) -> list[dict[str, Any]]:
        with self.connection.cursor(as_dict=True) as cursor:
            cursor.execute(sql, tuple(params) if params else None)
            return cursor.fetchall() or []

    def scalar(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        """Return the first column of the first row, or None.

        Uses a POSITIONAL cursor, not as_dict=True: pymssql raises
        ColumnsWithoutNamesError when a dict cursor meets an unnamed column, and
        `SELECT COUNT(*) FROM t` -- the single most common scalar query there is -- has
        no column name. Requiring every caller to write `AS anything` would be a rule
        that is only discovered by tripping over it.
        """
        with self.connection.cursor() as cursor:
            cursor.execute(sql, tuple(params) if params else None)
            row = cursor.fetchone()
            return None if row is None else row[0]

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> int:
        with self.connection.cursor() as cursor:
            cursor.execute(sql, tuple(params) if params else None)
            return cursor.rowcount

    # ── identity of this source incarnation ─────────────────────────────────────────

    def source_fingerprint(self) -> SourceFingerprint:
        row = self.query(
            """
            SELECT
                CAST(SERVERPROPERTY('ServerName') AS NVARCHAR(256)) AS server_name,
                CAST(d.service_broker_guid AS NVARCHAR(64))         AS database_guid,
                CONVERT(VARCHAR(23), d.create_date, 126)            AS database_created_at
            FROM sys.databases AS d
            WHERE d.database_id = DB_ID()
            """
        )[0]
        return SourceFingerprint(
            server_name=str(row["server_name"]),
            database_guid=str(row["database_guid"]),
            database_created_at=str(row["database_created_at"]),
        )

    # ── the snapshot that makes every read below safe ───────────────────────────────

    @contextmanager
    def snapshot(self) -> Iterator["SourceSnapshot"]:
        """Open one SNAPSHOT transaction and take every watermark inside it.

        THE ORDER HERE IS THE CORRECTNESS, and it is the part people get wrong.

        Inside a SNAPSHOT transaction the loader takes the change-tracking version and
        the high-water ceilings FIRST, then reads the base tables. Both halves observe
        the same committed state as of the transaction's start. So a write that commits
        while the read is in flight is:

            * invisible to this read  (the snapshot predates it), AND
            * above this run's stamp  (the stamp predates it too)

        which means it is picked up by the NEXT run. Exactly once, never lost, never
        double-applied with a value that has since moved on.

        THAT HOLDS FOR CHANGE TRACKING, whose versions are assigned at COMMIT. It does
        NOT hold for the IDENTITY high-water tables, and what breaks it is the counter
        rather than the ordering argued here. An IDENTITY value is assigned at INSERT,
        so a row can still be uncommitted when this snapshot opens and carry an id
        BELOW the ceiling the snapshot takes -- invisible to the read, and buried by
        the watermark. Measured, not supposed: see `high_water_ceiling`.

        Get this wrong in either direction and there is no error:
            * stamp taken AFTER the read  -> rows committed in between are skipped
                                             forever; the watermark has moved past them.
            * stamp taken outside a snapshot -> the read sees rows the stamp excludes,
                                             so they are applied twice, the second time
                                             potentially with a staler value than the
                                             first.

        SNAPSHOT (not REPEATABLE READ) because it takes no read locks: this is standing
        in for a production lending database, and an extract that blocks writers is an
        extract that gets switched off. ALLOW_SNAPSHOT_ISOLATION is turned on in
        01_schema.sql; without it this raises rather than silently degrading.
        """
        cursor = self.connection.cursor(as_dict=True)
        try:
            cursor.execute("SET TRANSACTION ISOLATION LEVEL SNAPSHOT;")
            cursor.execute("BEGIN TRANSACTION;")
            yield SourceSnapshot(self, cursor)
            cursor.execute("COMMIT TRANSACTION;")
        except BaseException:
            try:
                cursor.execute("ROLLBACK TRANSACTION;")
            except pymssql.Error:
                pass                       # the transaction is already gone
            raise
        finally:
            cursor.close()
            # Leave the connection at the server default so a later statement outside a
            # snapshot is not silently running under one.
            with self.connection.cursor() as reset:
                reset.execute("SET TRANSACTION ISOLATION LEVEL READ COMMITTED;")


class SourceSnapshot:
    """Reads taken inside one consistent SNAPSHOT transaction.

    Construct only via `Source.snapshot()`.
    """

    def __init__(self, source: Source, cursor: Any) -> None:
        self._source = source
        self._cursor = cursor

        # Taken FIRST, before any base-table read. See Source.snapshot.__doc__.
        self._change_tracking_version: int = self._fetch_scalar(
            "SELECT CHANGE_TRACKING_CURRENT_VERSION() AS v"
        )
        self._high_water_ceilings: dict[str, int | None] = {}

    # ── internals ───────────────────────────────────────────────────────────────────

    def _fetch_all(self, sql: str, params: Sequence[Any] | None = None) -> list[dict[str, Any]]:
        self._cursor.execute(sql, tuple(params) if params else None)
        return self._cursor.fetchall() or []

    def _fetch_scalar(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        rows = self._fetch_all(sql, params)
        if not rows:
            return None
        return next(iter(rows[0].values()))

    # ── the version stamp for this run ──────────────────────────────────────────────

    @property
    def change_tracking_version(self) -> int:
        """The version every change_tracking table's watermark advances to this run."""
        return int(self._change_tracking_version or 0)

    # ── arbitrary reads inside this snapshot ────────────────────────────────────────
    #
    # Public counterparts to Source.query / Source.scalar, for callers that need to read
    # something this class does not model. `pipeline/checks` is the reason they exist: the
    # reconciliation checks compare five tables against the warehouse and take seconds
    # doing it, so reading them through Source.query -- outside the snapshot -- could see
    # `customers` before a write and `transactions` after it and report a difference that
    # never existed at any single instant.
    #
    # Deliberately NOT a way to bypass the modelled readers below. Anything the loader
    # needs has a named method with the correctness argument attached to it; these are for
    # aggregates and metadata, which have no such argument to lose.

    def query(self, sql: str, params: Sequence[Any] | None = None) -> list[dict[str, Any]]:
        """Rows as dicts, read inside this snapshot."""
        return self._fetch_all(sql, params)

    def scalar(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        """First column of the first row, read inside this snapshot."""
        return self._fetch_scalar(sql, params)

    def min_valid_version(self, table: TableSpec) -> int:
        """The oldest version this table can still answer questions about.

        Below this, the change feed is not partially correct -- it is unusable, because
        cleanup has already removed the rows that would tell us what changed. SQL Server
        does not error if you ask anyway; CHANGETABLE simply returns less than the truth.
        Checking this is the difference between a reseed and silent divergence.
        """
        return int(
            self._fetch_scalar(
                "SELECT CHANGE_TRACKING_MIN_VALID_VERSION(OBJECT_ID(%s)) AS v",
                (table.qualified,),
            )
            or 0
        )

    def high_water_ceiling(self, table: TableSpec) -> int | None:
        """The upper bound for this run's append-only read, taken inside the snapshot.

        WHAT THE CLOSED WINDOW BUYS, precisely: the watermark cannot advance past a row
        that arrived after this read's view of the world was fixed. The ceiling is
        MAX(id) *as this snapshot sees it*, so the bound and the rows come out of one
        consistent view. The naive shape -- read `id > last_id` open-ended, then take
        MAX(id) in a separate statement once the read has finished -- counts everything
        that committed in between into the watermark without ever returning it. Those
        rows are gone, and nothing reports it. That race is real, and this closes it.

        WHAT IT DOES NOT BUY: it does not make an IDENTITY high-water mark safe under
        concurrent writers. An IDENTITY value is assigned when a row is INSERTED, not
        when its transaction COMMITS, so ids become visible out of order. Measured with
        two connections against this container -- the probe is kept, it is not a thought
        experiment:

            A inserts id 3, transaction LEFT OPEN
            B inserts id 4 and COMMITS
            C opens SNAPSHOT, which is exactly what this method does:
                ceiling MAX(id) = 4, rows visible = [1, 2, 4], id 3 visible = False
            A commits. id 3 is now visible to everyone, and 3 <= 4.

        A loader that advanced its watermark to 4 reads `id > 4` next run. Row 3 is never
        read again. Nothing raises; the probe row carried 50,000 cents.

        THE BOUND IS ON THE WRONG SIDE OF THE HAZARD. A snapshot-visible ceiling stops
        the window running off the TOP. The lost row is a GAP INSIDE the window, and no
        upper bound closes a gap beneath it.

        There is no MIN_ACTIVE_IDENTITY, and that is the whole of the difficulty.
        rowversion has MIN_ACTIVE_ROWVERSION() precisely so a reader can put its ceiling
        BELOW every in-flight write; SQL Server ships no equivalent for IDENTITY. So this
        is not a tuning problem to be solved by picking the ceiling more cleverly -- it
        is a property of the column the watermark is built on. (The rowversion strategy
        was cut from this exercise. That function is the argument for why it would be the
        right call on a source with real write concurrency.)

        WHY THIS SHIPS ANYWAY, said plainly rather than glossed:
          * Change Tracking, used for the three tables whose rows mutate, assigns its
            versions at COMMIT and has no such hole.
          * On the two append-only tables the gap is DETECTABLE with no extra
            bookkeeping -- COUNT(*) over the loaded window against MAX(id) - MIN(id) + 1
            -- and the scorecard's contiguity check reports it. A rolled-back insert
            burns an IDENTITY value permanently, so that check is a heuristic with a
            tolerance and never a proof.
          * This fixture is single-writer, so the hole is unreachable here and would be
            routine in production. Detecting it and saying so beats claiming it cannot
            happen.
        """
        if table.name not in self._high_water_ceilings:
            self._high_water_ceilings[table.name] = self._fetch_scalar(
                f"SELECT MAX([{table.watermark_column}]) AS ceiling FROM {table.qualified}"
            )
        return self._high_water_ceilings[table.name]

    # ── reads ───────────────────────────────────────────────────────────────────────

    def read_full_snapshot(self, table: TableSpec) -> list[dict[str, Any]]:
        """Read the whole table. Used for run 1 only, on change_tracking tables.

        Run 1 is a snapshot read, not a change-feed replay, because capture is enabled
        AFTER the seed (see 03_enable_capture.sql): asking CHANGETABLE for changes since
        version 0 on a freshly-enabled table correctly returns nothing at all. That is
        not a bug to work around, it is the reason the initial load exists as its own
        mode -- and ops.load_run records read_mode='snapshot' for run 1 so the
        distinction is visible in the output rather than implied.
        """
        return self._fetch_all(
            f"SELECT {table.column_list_sql} FROM {table.qualified}"
        )

    def read_changes(self, table: TableSpec, since_version: int) -> list[ChangeRow]:
        """Read the change feed for a change_tracking table.

        LEFT JOIN, not INNER JOIN, and that is not a stylistic preference: a deleted row
        is present in CHANGETABLE and absent from the base table, so an INNER JOIN drops
        every delete. The pipeline would then never remove anything, and the warehouse
        would accumulate customers who no longer exist -- while row counts still
        reconciled, because nothing was ever missing, only extra.

        The seed makes that failure reachable: `customers.is_deleted` exists and no row
        is ever set to 1, because the application hard-deletes. Churn day 1 hard-deletes
        13 customers.
        """
        key_columns = list(table.primary_key)
        ct_keys = ", ".join(f"ct.[{c}] AS [ct_{c}]" for c in key_columns)
        base_columns = ", ".join(
            f"t.[{c}]" for c in table.columns if c not in key_columns
        )
        join_predicate = " AND ".join(f"ct.[{c}] = t.[{c}]" for c in key_columns)
        select_base = f", {base_columns}" if base_columns else ""

        rows = self._fetch_all(
            f"""
            SELECT
                ct.SYS_CHANGE_OPERATION AS _operation,
                {ct_keys}{select_base}
            FROM CHANGETABLE(CHANGES {table.qualified}, %s) AS ct
            LEFT JOIN {table.qualified} AS t
                   ON {join_predicate}
            """,
            (since_version,),
        )

        changes: list[ChangeRow] = []
        for row in rows:
            operation = str(row["_operation"])
            key = tuple(row[f"ct_{c}"] for c in key_columns)
            if operation == "D":
                changes.append(ChangeRow(operation="D", key=key, values=None))
                continue
            values = {c: row[f"ct_{c}"] for c in key_columns}
            values.update({c: row[c] for c in table.columns if c not in key_columns})
            changes.append(ChangeRow(operation=operation, key=key, values=values))
        return changes

    def read_high_water(
        self, table: TableSpec, since_value: int, ceiling: int | None
    ) -> list[dict[str, Any]]:
        """Read an append-only table over the CLOSED window (since_value, ceiling].

        Both bounds are required. See `high_water_ceiling` for what an open upper bound
        costs and why it costs it silently.
        """
        if ceiling is None or ceiling <= since_value:
            return []
        return self._fetch_all(
            f"""
            SELECT {table.column_list_sql}
            FROM {table.qualified}
            WHERE [{table.watermark_column}] >  %s
              AND [{table.watermark_column}] <= %s
            ORDER BY [{table.watermark_column}]
            """,
            (since_value, ceiling),
        )
